<?php
/**
 * Implementation of hook_menu()
 */
function ubercoova_menu() {
  $items = array();
  $items['admin/settings/ubercoova'] = array(
    'title' => 'UberCoova',
    'description' => 'Configure settings for the UberCoova module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ubercoova_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer ubercoova'),
    'file' => 'includes/ubercoova.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_perm()
 */
function ubercoova_perm() {
  return array('administer ubercoova');
}

/**
 * Implementation of hook_user()
 *
 * Verify user login against FreeRADIUS MySQL backend
 * and update in Drupal if required.
 *
 * Populate an account tab with usage/remaining info.
 */
function ubercoova_user($op, &$edit, &$account, $category = NULL) {

}

/**
 * Implementation of hook_uc_checkout_complete()
 *
 * When product purchase complete, transpose purchased
 * quota to FreeRADIUS MySQL backend.
 */
function ubercoova_uc_checkout_complete($order, $account) {

}
